2023-10-10 14:19:43,183 DEBUG    root            Loaded Command Group: ['gcloud', 'compute']
2023-10-10 14:19:43,185 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'instances']
2023-10-10 14:19:43,288 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'instances', 'create']
2023-10-10 14:19:43,362 DEBUG    root            Running [gcloud.compute.instances.create] with arguments: [--boot-disk-size: "536870912000", --image-family: "tf-1-15-5", --image-project: "ml-images", --machine-type: "n1-highmem-8", --maintenance-policy: "TERMINATE", --restart-on-failure: "True", --zone: "asia-southeast1-a", INSTANCE_NAMES:1: "['pegasus']"]
2023-10-10 14:19:43,374 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): compute.googleapis.com:443
2023-10-10 14:19:43,853 DEBUG    urllib3.connectionpool https://compute.googleapis.com:443 "GET /compute/v1/projects/pegasus-401519/zones/asia-southeast1-a?alt=json HTTP/1.1" 200 None
2023-10-10 14:19:43,859 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): compute.googleapis.com:443
2023-10-10 14:19:44,451 DEBUG    urllib3.connectionpool https://compute.googleapis.com:443 "GET /compute/v1/projects/pegasus-401519?alt=json HTTP/1.1" 200 None
2023-10-10 14:19:44,465 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): compute.googleapis.com:443
2023-10-10 14:19:46,748 DEBUG    urllib3.connectionpool https://compute.googleapis.com:443 "POST /compute/v1/projects/pegasus-401519/zones/asia-southeast1-a/instances?alt=json HTTP/1.1" 200 None
2023-10-10 14:19:46,752 DEBUG    root            Operations to inspect: [(<Operation
 id: 5259449720686292677
 insertTime: '2023-10-10T01:49:46.614-07:00'
 kind: 'compute#operation'
 name: 'operation-1696927784559-60758c9cee417-5a26f192-444baf25'
 operationType: 'insert'
 progress: 0
 selfLink: 'https://www.googleapis.com/compute/v1/projects/pegasus-401519/zones/asia-southeast1-a/operations/operation-1696927784559-60758c9cee417-5a26f192-444baf25'
 startTime: '2023-10-10T01:49:46.614-07:00'
 status: StatusValueValuesEnum(RUNNING, 2)
 targetId: 5566877960700997318
 targetLink: 'https://www.googleapis.com/compute/v1/projects/pegasus-401519/zones/asia-southeast1-a/instances/pegasus'
 user: 'hardiksharmah73@gmail.com'
 warnings: []
 zone: 'https://www.googleapis.com/compute/v1/projects/pegasus-401519/zones/asia-southeast1-a'>, 3)]
2023-10-10 14:19:46,756 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): compute.googleapis.com:443
2023-10-10 14:19:53,272 DEBUG    urllib3.connectionpool https://compute.googleapis.com:443 "POST /compute/v1/projects/pegasus-401519/zones/asia-southeast1-a/operations/operation-1696927784559-60758c9cee417-5a26f192-444baf25/wait?alt=json HTTP/1.1" 200 None
2023-10-10 14:19:53,277 DEBUG    root            Operations to inspect: [(<Operation
 endTime: '2023-10-10T01:49:53.153-07:00'
 error: <ErrorValue
 errors: [<ErrorsValueListEntry
 code: 'ZONE_RESOURCE_POOL_EXHAUSTED'
 errorDetails: [<ErrorDetailsValueListEntry
 help: <Help
 links: [<HelpLink
 description: 'Troubleshooting documentation'
 url: 'https://cloud.google.com/compute/docs/resource-error'>]>>, <ErrorDetailsValueListEntry
 localizedMessage: <LocalizedMessage
 locale: 'en-US'
 message: 'A n1-highmem-8 VM instance is currently unavailable in the asia-southeast1-a zone. Alternatively, you can try your request again with a different VM hardware configuration or at a later time. For more information, see the troubleshooting documentation.'>>, <ErrorDetailsValueListEntry
 errorInfo: <ErrorInfo
 domain: 'compute.googleapis.com'
 metadatas: <MetadatasValue
 additionalProperties: [<AdditionalProperty
 key: 'zonesAvailable'
 value: ''>, <AdditionalProperty
 key: 'vmType'
 value: 'n1-highmem-8'>, <AdditionalProperty
 key: 'zone'
 value: 'asia-southeast1-a'>, <AdditionalProperty
 key: 'attachment'
 value: ''>]>
 reason: 'resource_availability'>>]
 message: "The zone 'projects/pegasus-401519/zones/asia-southeast1-a' does not have enough resources available to fulfill the request.  Try a different zone, or try again later.">]>
 httpErrorMessage: 'SERVICE UNAVAILABLE'
 httpErrorStatusCode: 503
 id: 5259449720686292677
 insertTime: '2023-10-10T01:49:46.614-07:00'
 kind: 'compute#operation'
 name: 'operation-1696927784559-60758c9cee417-5a26f192-444baf25'
 operationType: 'insert'
 progress: 100
 selfLink: 'https://www.googleapis.com/compute/v1/projects/pegasus-401519/zones/asia-southeast1-a/operations/operation-1696927784559-60758c9cee417-5a26f192-444baf25'
 startTime: '2023-10-10T01:49:46.614-07:00'
 status: StatusValueValuesEnum(DONE, 0)
 targetId: 5566877960700997318
 targetLink: 'https://www.googleapis.com/compute/v1/projects/pegasus-401519/zones/asia-southeast1-a/instances/pegasus'
 user: 'hardiksharmah73@gmail.com'
 warnings: []
 zone: 'https://www.googleapis.com/compute/v1/projects/pegasus-401519/zones/asia-southeast1-a'>, 3)]
2023-10-10 14:19:53,277 DEBUG    root            Chosen display Format:yaml
2023-10-10 14:19:53,280 DEBUG    root            (gcloud.compute.instances.create) Could not fetch resource:
---
code: ZONE_RESOURCE_POOL_EXHAUSTED
errorDetails:
- help:
    links:
    - description: Troubleshooting documentation
      url: https://cloud.google.com/compute/docs/resource-error
- localizedMessage:
    locale: en-US
    message: A n1-highmem-8 VM instance is currently unavailable in the asia-southeast1-a
      zone. Alternatively, you can try your request again with a different VM hardware
      configuration or at a later time. For more information, see the troubleshooting
      documentation.
- errorInfo:
    domain: compute.googleapis.com
    metadatas:
      attachment: ''
      vmType: n1-highmem-8
      zone: asia-southeast1-a
      zonesAvailable: ''
    reason: resource_availability
message: The zone 'projects/pegasus-401519/zones/asia-southeast1-a' does not have
  enough resources available to fulfill the request.  Try a different zone, or try
  again later.
Traceback (most recent call last):
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/surface/compute/instances/create.py", line 699, in Run
    return compute_client.MakeRequests(requests)
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/client_adapter.py", line 156, in MakeRequests
    utils.RaiseToolException(
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 139, in RaiseToolException
    RaiseException(problems, calliope_exceptions.ToolException, error_message)
  File "/home/devilunraveled/GoogleCloud/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 148, in RaiseException
    raise exception(
googlecloudsdk.calliope.exceptions.ToolException: Could not fetch resource:
---
code: ZONE_RESOURCE_POOL_EXHAUSTED
errorDetails:
- help:
    links:
    - description: Troubleshooting documentation
      url: https://cloud.google.com/compute/docs/resource-error
- localizedMessage:
    locale: en-US
    message: A n1-highmem-8 VM instance is currently unavailable in the asia-southeast1-a
      zone. Alternatively, you can try your request again with a different VM hardware
      configuration or at a later time. For more information, see the troubleshooting
      documentation.
- errorInfo:
    domain: compute.googleapis.com
    metadatas:
      attachment: ''
      vmType: n1-highmem-8
      zone: asia-southeast1-a
      zonesAvailable: ''
    reason: resource_availability
message: The zone 'projects/pegasus-401519/zones/asia-southeast1-a' does not have
  enough resources available to fulfill the request.  Try a different zone, or try
  again later.

2023-10-10 14:19:53,280 ERROR    root            (gcloud.compute.instances.create) Could not fetch resource:
---
code: ZONE_RESOURCE_POOL_EXHAUSTED
errorDetails:
- help:
    links:
    - description: Troubleshooting documentation
      url: https://cloud.google.com/compute/docs/resource-error
- localizedMessage:
    locale: en-US
    message: A n1-highmem-8 VM instance is currently unavailable in the asia-southeast1-a
      zone. Alternatively, you can try your request again with a different VM hardware
      configuration or at a later time. For more information, see the troubleshooting
      documentation.
- errorInfo:
    domain: compute.googleapis.com
    metadatas:
      attachment: ''
      vmType: n1-highmem-8
      zone: asia-southeast1-a
      zonesAvailable: ''
    reason: resource_availability
message: The zone 'projects/pegasus-401519/zones/asia-southeast1-a' does not have
  enough resources available to fulfill the request.  Try a different zone, or try
  again later.

